goorea/muscleman-api

index.ts, package.json, tsconfig.json, yarn.lock
프로젝트 내의 파일을 `import` 할 때 절대 경로 및 별칭을 사용하여 `import`할 수 있습니다.
- `tsconfig-paths` 패키지를 설치하여 타입스크립트(`tsconfig.json`) 설정에 경로관련 이슈들을 해결합니다.
- `package.json`의 스크립트들의 환경변수들을 타입스크립트(`tsconfig.json`) 설정 파일로 옮겼습니다.
`package.json`의 `start` 스크립트는 서버를 구동하기만하고 서버의 변경사항이 있을 때마다 반영하는 `nodemon`은 `watch` 스크립트로 빼놨는데 이게 과연 맞는 구조일지... 보통 개발할 때는 `watch`만 사용할텐데 스크립트 실행할 때 `start`보다 타자치는게 많아서 고민된다.
resolve #12
=> [style] 별칭 절대 경로

index.ts, jest.config.ts, package.json, src/boostrap.ts, src/graphql/resolvers.ts, src/graphql/schema.ts, src/graphql/typeDefs.ts, src/models/User/UserFactory.ts, src/models/User/UserResolver.ts, src/models/User/UserTypeDef.ts, src/models/User/index.ts, tests/feature/connect.test.ts, tests/graphql.ts, tests/setup.ts, tsconfig.json, yarn.lock
추후에 모든 api에 대해 테스트를 진행하기 위해 jest로 테스트 환경을 구축합니다.
- 루트 폴더에 테스트를 위한 `tests` 폴더가 생겼기 때문에 typescript 별칭 경로 `~`에서 `@src/`로 수정 및 `@tests/` 추가
- [jest](https://jestjs.io/) 설치
- 하나의 테스트 파일에 데이터베이스 공유. 테스트가 끝나면 `mongo-memory-server`가 종료됨. Test Suit마다 독립성을 보장해주므로 테스트 환경에서의 데이터의 일관성을 보장하기 위함
- `tests/setup.ts` 테스트를 하기 전에 데이터베이스 의존성 설정
- 각 모델의 mock데이터를 손쉽게 만들기 위해 [faker](https://github.com/Marak/Faker.js#readme) 설치
- 현재 기본적인 테스트를 위해 `User`모델의 틀만 잡아놨다. [추후](https://github.com/jhs851/muscleman-api/issues/17)에 재정의하도록 한다.
- `graphQL`과 `mongo memory server`가 테스트 환경에서 잘 작동하는지 확인
- 테스트 환경에서 `graphQL`을 작동하기 위한 `tests/graphql.ts` 파일
- `UserResolve`의 `Mutation`들의 `rootValue`가 `any` 타입으로 정의되있다. #16 을 해결하고 나면 자동으로 해결될 것으로 보인다.
- 테스트 코드에서 `graphQL`의 쿼리를 쓸 때 좀 더 간결하게 쓸 수 있게 하는 패키지가 있을 것으로 보인다. #16 해결 후에 보도록 하자. …
=> [feat] gql 테스트 환경 jest로 구축

README.md, package.json, src/factories/UserFactory.ts, src/factories/types/UserFactoryInput.ts, src/limits/UserLimit.ts, src/models/Model.ts, src/models/User.ts, src/resolvers/UserResolver.ts, src/resolvers/types/UserInput.ts, src/schema.ts, src/types/enums.ts, tests/feature/connect.test.ts, tests/feature/get-users.test.ts, tests/feature/registeration.test.ts, tests/setup.ts, tests/unit/user.test.ts, yarn.lock
#6 으로 인해 기본적인 틀만 구성되있던 `User`모델을 서비스 성격에 맞게 재정의합니다.
- `README.md` 파일에 test 스크립트
- 비밀번호 암호화는 [bcrypt](https://github.com/kelektiv/node.bcrypt.js) 사용
- `User` 모델에 **이름**, **이메일**, **닉네임**, **비밀번호**, **나이**, **성별**, **키**, **몸무게**, **지방량**, **골격근량**, **전화번호**, **프로필 이미지 경로** 필드 추가
- `UserInput`, `UserFactoryInput`, `UserFactory`도 같이 추가
- 필드에 대한 제한 사항(글자길이, 숫자 최소값 최대값 등)을 위한 `UserLimit`
- 각각 필드들에 유효성 검사 추가
- 추후에 모든 모델들이 `_id`, `created_at`, `updated_at`은 반드시 사용할 것이라 생각하여 `Model` 클래스 생성 및 `User`모델 상속
- Query 및 Mutation 재정의
- Query:
- 모든 사용자를 불러오는 `users`
- 특정 사용자만 불러오는 `user`
- Mutation:
- 회원가입(사용자 추가)하는 `register`
- 테스트 추가
- 성별을 위한 `Gender` enum 타입 추가
- `faker` 한국어로 변경
- **나이** 대신 **생년월일**로 변경
하나의 커밋에 너무 많은 업데이트가 있는 듯 하네유
resolve #17
=> [feat] User 모델 재정의

src/errors/AuthenticationError.ts, src/errors/ForbiddenError.ts, src/middlewares/AuthenticateMiddleware.ts, src/middlewares/EnsureEmailIsVerifiedMiddleware.ts, src/middlewares/GuestMiddleware.ts, src/resolvers/UserResolver.ts, tests/feature/get-users.test.ts, tests/feature/logination.test.ts, tests/feature/registeration.test.ts, tests/feature/token-refreshation.test.ts, tests/feature/verification.test.ts
에러를 발생시킬 때 각 성격에 맞는 에러를 반환하기 위해 에러 클래스 생성
- `apollo-server`의 `AuthenticationError`를 상속받는 `AuthenticationError` 클래스 생성(에러 메세지 통일)
- `apollo-server`의 `ForbiddenError`를 상속받는 `ForbiddenError` 클래스 생성(에러 메세지 통일)
- `type-graphql`의 `UnauthorizedError` 사용하던 것을 `AuthenticationError`로 변경
- `type-graphql`의 `ForbiddenError` 사용하던 것을 이번에 만든 `ForbiddenError`로 변경
- **`UserResolver`에서 사용자를 찾고, 사용자가 없으면 에러를 발생시키던 것을 mongoose 쿼리의 `orFail` 메서드를 사용함**
소셜 로그인했던 사용자가 네이티브 로그인을 요청했을 때
네이티브 로그인 한 사용자의 비밀번호가 틀렸을 때
같은 인스턴스의 에러를 반환하고 있다. 클라이언트쪽에서 구분하기 어려울 듯
resolve #31
=> [refactor] 성격에 맞는 에러 생성

.eslintrc.js, src/models/Training.ts, src/models/User.ts, src/models/types/Training.ts, src/models/types/User.ts, src/resolvers/UserResolver.ts, tests/helpers.ts, tests/unit/user.test.ts
typegoose 쿼리 후 반환하는 `EnforceDocument`에 메서드와 쿼리헬퍼를 타입힌팅한다
- 모든 모델들에게 메서드와 쿼리헬퍼 인터페이스를 상속
- 모든 모델이 메서드와 쿼리헬퍼 인터페이스의 값이 있는 것이 아니기 때문에 `eslint` `@typescript-eslint/no-empty-interface` 규칙을 수정
- 기존에 만들어져있던 `Training` 모델에 `typegoose` 모델 생성 선언이 없었던 것 수정
- `User` 모델에 재사용성이 다분한 JWT 토큰 반환 기능을 메서드로 뺌
- 테스트 추가
resolve #40
=> [refactor] 모델들 재정의

package.json, src/context.ts, src/resolvers/UserResolver.ts, tests/graphql.ts
이전엔 서버 `context`에 사용자의 `_id`만 저장되고 있었는데 모든 사용자 정보를 저장
- 테스트 시 `context`에 필요한 mock 요청, 응답을 위해 `express` 설치
- `context`의 `user`키 타입 변경 및 리턴 값 변경
- `context`의 `user._id`를 사용해 사용자 정보를 가져오던 모든 코드 리팩토링
resolve #39
=> [refactor] apollo context에 사용자의 모든 정보 저장

src/bootstrap.ts, src/factories/UserFactory.ts, src/schema.ts, src/types/enums.ts
`enum` 값들을 모두 대문자로 변경
- `type-graphql`의 `enum`을 등록하는 `registerEnumType`을 `enum.ts` 파일로 이동
-  `registerEnumType`을 사용하는 파일에 `reflect-metadata`를 임포트해야해서 이동
- 모든 `enum` 값 대문자로 변경
resolve #43
=> [style] enum 값 대문자로 변경

src/errors/ForbiddenError.ts, src/factories/TrainingFactory.ts, src/factories/types/TrainingFactoryInput.ts, src/limits/TrainingLimit.ts, src/middlewares/GuestMiddleware.ts, src/models/Training.ts, src/resolvers/TrainingResolver.ts, src/resolvers/UserResolver.ts, src/resolvers/types/TrainingInput.ts, tests/feature/create-training.test.ts, tests/feature/logination.test.ts, tests/feature/registeration.test.ts, tests/feature/token-refreshation.test.ts, tests/feature/verification.test.ts, tests/helpers.ts
운동 종목 추가 기능
- `type-graphql`의 `@Authorized` 데코레이터가 권한 문제로 오류를 발생시킬 때 `ForbiddenError`를 반환한다. 여러개 쓰는 것보다 한개로 통일하는게 좋아보여 기존에 생성했었던 `ForbiddenError` 제거
- `TrainingFactory` 추가
- `TrainingFactoryInput` 추가
- `TrainingLimit` 추가
- `Training` 모델에 `name` prop unique로 변경
- `TrainingResolve` 추가
- `createTraining` mutation 추가
- 테스트 추가
- `UserResolve`의 mutation들 리턴타입 조금 더 명시적으로 수정
- `TrainingInput` 추가
- 테스트 환경에서 사용자 `JWT` 토큰을 반환하던 `signIn` 함수에 사용자 권한을 추가할 수 있도록 수정
resolve #36
=> [feat] 운동종목 추가

src/limits/TrainingLimit.ts, src/resolvers/TrainingResolver.ts, src/resolvers/types/TrainingInput.ts, tests/feature/update-training.test.ts
관리자 권한을 가지고 있는 사용자가 이미 존재하는 운동종목을 수정 또는 삭제
- `type-graphql`에서 빈 스트링에 대한 유효성 검사를 안함
- `MinLength` 데코레이터로 확인하는 쪽으로 변경
- `updateTraining`, `deleteTraining` mutation 추가
- mutation에 관한 테스트 추가
resolve #37
=> [feat] 운동종목 수정, 삭제

src/limits/TrainingLimit.ts, src/resolvers/types/LoginInput.ts, src/resolvers/types/TrainingInput.ts, src/resolvers/types/UserInput.ts, src/resolvers/types/VerifyInput.ts
유효하지 않거나 필요하지 않은 `Validation Decoratr` 제거 및 수정
- query나 mutation에서 반드시 필요한 프로퍼티가 값이 undefined라면 `TypeGraphQL`에서 유효성 검사를 하기전에 `GraphQL`에서 `GraphQLError`를 반환한다.
- 결과적으로는 이를 이용하여 필요없는 데코레이터들을 삭제하거나 수정함
- `@IsDefined`: `required`인 프로퍼티에 `undefined`나 `null`이 온다면 `GraphQL`에서 에러를 반환하기 때문에 삭제
- `@IsNotEmpty`: `GraphQL`에서 빈문자열은 검사하지 않는다. `required` 프로퍼티이면서 `string` 타입이면 추가한다.
- 만약 `@IsEmail`이나 `@Min`, `@Length` 등의 문자열의 추가 검사를 한다면 추가할 필요없다
- `@IsString`, `@IsInt`, `@IsEnum` 등의 프로퍼티의 타입 검사는 이미 `GraphQL`에서 한다. 필요없다.
클라이언트에서 에러를 받을 때 어떤 에러인지 확인하기 어렵다. 추후에 에러핸들링을 통해 좀 더 명시적인 에러를 반환하도록 #52 이슈 등록
resolve #51
=> [refactor] Validation Decorator 수정

src/factories/PlanFactory.ts, src/factories/SetFactory.ts, src/limits/PlanLimit.ts, src/models/Plan.ts, src/models/Set.ts, src/models/Training.ts, src/plugins/jwt.ts, src/resolvers/PlanResolver.ts, src/resolvers/types/PlanInput.ts, src/resolvers/types/SetInput.ts, tests/feature/create-plans.test.ts, tests/feature/get-users.test.ts, tests/feature/update-training.test.ts, tests/helpers.ts
운동 계획 생성에 대한 `mutation` 및 테스팅
- `PlanFactory` 생성
- `SetFactory` 생성
- `PlanInput` 생성
- `SetInput` 생성
- 제한 `PlanLimit` 생성
- `PlanResolver` 및 `createPlan` `mutation` 생성
- 관련 테스트 추가
- `Plan` 모델에서 `Set` 모델은 테이블에 저장하지 않기 때문에 `Ref` 키워드를 사용할 수 없고 `Set`는 `mongoose`의 스칼라타입이 아니기 때문에 `type`에 선언할 수 없다. `mongoose.Schema.Types.Mixed` 으로 정의
- `Set` 모델에 무게, 시간, 거리는 `Float` 타입으로 변경
- `_id`에서 `toString` 메서드말고 `toHexString`을 쓰도록 변경
resolve #55
=> [feat] 운동 계획을 생성

src/factories/PlanFactory.ts, src/models/Plan.ts, src/resolvers/types/PlanInput.ts, tests/feature/create-plans.test.ts
`Plan` 모델에 `complete` 필드 추가
- `Plan` 모델에 `complete` 필드 추가
- `PlanInput`에 `complete` 필드 추가
- `PlanFactory`에 `complete` 추가
`complete`만 토글하는 `mutation`을 만들어야하나?
resolve #59
=> [feat] 운동 계획 모델에 완료 여부 데이터 추가

src/models/Model.ts, src/plugins/jwt.ts, src/resolvers/PlanResolver.ts, src/resolvers/TrainingResolver.ts, src/scalars/ObjectIdScalar.ts, src/schema.ts
기존에는 `Model`의 `id`로 `mongodb`의 `ObjectId`를 사용했었는데 `mongoose`에서 여러 타입 에러들이 발생하기 때문에 `mongoose`의 `ObjectId`로 변경
`mongodb`의 `ObjectId`를 사용하던 것을 모두 `mongoose`의 `ObjectId`로 변경
resolve #63
=> [refactor] mongoose ObjectId 로 pk 변경

src/models/Plan.ts, src/models/Training.ts, src/models/User.ts, src/models/hooks/training-hooks.ts, src/models/hooks/user-hooks.ts, src/types/hooks.d.ts, tests/feature/registeration.test.ts, tests/unit/training.test.ts, tests/unit/user.test.ts
`User` 모델과 `Training` 모델이 삭제되었을 때 연결된 `Plan` 모델들도 같이 삭제
- `delete` 훅에서 다른 모델을 삭제하려고 하면 `Option "ref" for "Plan.user" is null/undefined! [E005]` 에러가 발생한다. [구글링](https://github.com/typegoose/typegoose/issues/427) 해보니 문자열로 하드코딩하면 문제가 해결됨
- `Training` 훅 추가
- `User` 훅 추가
- 관련 테스트 추가
resolve #62
=> [feat] 관계된 모델들이 삭제나 수정을 했을 때의 훅 추가

src/resolvers/PlanResolver.ts, tests/feature/get-plans.test.ts, tests/feature/get-users.test.ts
`plans` `query` 추가
- `PlanResolver`에 `plans` `query` 추가
- 관련 테스트 추가
resolve #60
=> [feat] 모든 운동 계획 가져오는 query 추가

src/factories/PlanFactory.ts, src/factories/TrainingFactory.ts, src/factories/UserFactory.ts, src/resolvers/PlanResolver.ts, src/resolvers/TrainingResolver.ts, src/resolvers/UserResolver.ts, src/resolvers/types/CreatePlanInput.ts, src/resolvers/types/CreateTrainingInput.ts, src/resolvers/types/RegisterInput.ts, src/resolvers/types/UpdatePlanInput.ts, src/resolvers/types/UpdateTrainingInput.ts, tests/feature/create-plans.test.ts, tests/feature/create-training.test.ts, tests/feature/registeration.test.ts, tests/feature/update-plans.test.ts, tests/feature/update-trainings.test.ts, tests/helpers.ts, tests/unit/user.test.ts
각 Input 인스턴스 성격에 맞게 이름 변경
- `PlanInput` -> `CreatePlanInput` 이름 변경
- 모든 필드가 `nullable`인 `UpdatePlanInput` 생성
- `TrainingInput` -> `CreateTrainingInput` 이름 변경
- 모든 필드가 `nullable`인 `UpdateTrainingInput` 생성
- `UserInput` -> `RegisterInput` 이름 변경
- 관련 테스트 수정
resolve #91
=> [style] 각 Input 인스턴스 성격에 맞게 이름 변경

src/models/Plan.ts, src/models/hooks/plan-hooks.ts, src/models/types/Plan.ts, src/models/types/WeightSet.ts, tests/unit/plan.test.ts
`Plan` 모델에 최대 무게를 토글하는 훅 추가
- `one_rm` 프로퍼티 `Float`으로 타입 변경
- `Plan` 모델
- 메서드 추가
- `hasWeightSets`: 해당 운동 계획이 중량 운동인지 확인
- `getOneRM`: 해당 운동 계획의 최대 무게를 반환
- 훅 추가
- `complete`의 상태가 변경되었을 때 `one_rm` 프로퍼티 토글
- `weight`와 `count` 값이 `required`인 `WeightSet` 인터페이스 생성
resolve #89
=> [feat] Plan 모델에 훅을 추가하여 최대 무게 토글

package.json, src/factories/PlanFactory.ts, src/limits/PlanLimit.ts, src/models/Plan.ts, src/resolvers/PlanResolver.ts, src/resolvers/types/CreatePlanInput.ts, src/resolvers/types/UpdatePlanInput.ts, tests/feature/create-plans.test.ts, tests/feature/get-plans.test.ts, tests/feature/update-plans.test.ts, yarn.lock
오늘의 운동 쿼리 생성
- 오늘의 운동인지 확인하기 위해 [momentjs](https://momentjs.com/) 설치
- `Plan` 모델의 `planDate` -> `plannedAt` 으로 변경
- 관련 테스트 수정
- 해당 사용자의 오늘의 운동 계획들을 반환하는 `todayPlans` 쿼리 생성
- 관련 테스트 작성
`plans` 쿼리를 이용한 다음 클라이언트에서 `filter`해서 사용할 수도 있다. 하지만 오늘의 운동 계획은 모든 운동 계획 페이지에서 오늘 날짜의 운동을 수정했을 때 홈쪽에서의 오늘의 운동 계획도 변경되어야하기 때문에 `recoil`로 전역 상태 관리를 할 가능성이 크다. `recoil`의 `default` 데이터를 넣기 위해선 `RecoilProvider`에서 오늘의 운동 계획들을 불러어 하는데 앱을 실행할 때마다 모든 운동 계획들을 전부다 가져오는건 리소스 낭비라고 생각한다.
resolve #111
=> [feat] 오늘의 운동 쿼리 생성

src/models/Model.ts, src/models/Plan.ts, src/models/Training.ts, src/models/User.ts
`Model`에 `createdAt`, `updatedAt` 프로퍼티 추가 및 `timestamps` 옵션 추가
- `Model`에 `createdAt`, `updatedAt` 프로퍼티 추가
- `Model`에 `timestamps` `schmeOption` 추가
- `User`, `Training`, `Plan` 모델에 `timestamps` 옵션 제거
resolve #116
=> [fix] Model에 createdAt updatedAt 프로퍼티 추가

src/factories/TrainingFactory.ts, src/models/Training.ts, src/resolvers/types/CreateTrainingInput.ts, src/resolvers/types/UpdateTrainingInput.ts, src/types/enums.ts, tests/feature/create-training.test.ts
중량운동, 맨몸운동, 유산소운동 등을 구분할 수 있도록 `Training`모델에 `category` 프로퍼티를 추가합니다.
- `TrainingCategory` `enum` 추가
- `Training`, `TrainingFactory`, `CreateTrainingInput`, `UpdateTrainingInput`에 `category` 프로퍼티 추가
- 관련 테스트 수정 및 추가
`Training`의 `category`에 따라 다이나믹한 `Volumn` 프로퍼티들을 불러올 수 있을것인가...!
resolve #120
=> [feat] 중량운동, 맨몸운동, 유산소운동 구분

src/factories/PlanFactory.ts, src/factories/VolumeFactory.ts, src/models/Plan.ts, src/models/Volume.ts, src/models/WeightVolume.ts, src/models/hooks/plan-hooks.ts, src/models/hooks/training-hooks.ts, src/models/hooks/volume-hooks.ts, src/resolvers/PlanResolver.ts, src/resolvers/VolumeResolver.ts, src/resolvers/types/CreatePlanInput.ts, src/resolvers/types/UpdatePlanInput.ts, src/resolvers/types/VolumeInput.ts, tests/feature/create-plans.test.ts, tests/feature/get-plans.test.ts, tests/feature/update-plans.test.ts, tests/unit/plan.test.ts, tests/unit/training.test.ts, tests/unit/volume.test.ts
`Volume`모델의 `training`, `complete`, `oneRM` 속성을 `Plan`모델로 이동
- `training`, `complete`, `oneRM` 속성 이동
- `VolumeFactory` -> `PlanFactory`
- `Volume`모델 -> `Plan`모델
- `VolumeResolver` -> `PlanResolver`
- `VolumeInput` -> `CreatePlanInput`, `UpdatePlanInput`
- `setOneRM` 훅을 `Plan` 모델로 이동
- 운동 종목이 삭제 되었을 때 해당 종목의 운동 계획이 삭제되도록 `Training` 훅 변경
- 관련 테스트 수정
resolve #126
=> [feat] Volume모델의 training, complete, oneRM Plan모델로 이동

src/resolvers/TrainingResolver.ts, src/resolvers/types/CreateTrainingInput.ts, tests/feature/get-trainings.test.ts
모든 운동 종목을 조회할 수 있는 `trainings` 쿼리를 추가
-  `TrainingResolver`내에 `trainings` 쿼리 추가
- 관련 테스트 추가
resolve #128
=> [feat] trainings 쿼리 추가

src/factories/PlanFactory.ts, src/factories/VolumeFactory.ts, src/models/Plan.ts, src/models/Volume.ts, src/models/hooks/plan-hooks.ts, src/models/hooks/volume-hooks.ts, src/resolvers/PlanResolver.ts, src/resolvers/VolumeResolver.ts, src/resolvers/types/PlanInput.ts, src/resolvers/types/VolumeInput.ts, tests/feature/create-plans.test.ts, tests/feature/create-volumes.test.ts, tests/feature/get-plans.test.ts, tests/feature/get-volumes.test.ts, tests/unit/plan.test.ts, tests/unit/volume.test.ts
- `Plan` 모델의 `complete`를 제거하고 `Volume` 모델에 추가하여 운동 볼륨 단위로 완료를 확인할 수 있도록 한다.
- `getOneRM` `query`가 `PlanResolver`에서 해결하고 있는 것을 `VolumeResolver`에서 해결하도록 변경
- `Plan` 모델의 `complete`, `oneRM` 속성 제거
- `PlanFactory`, `PlanInput`
- `Plan` 모델의 `setOneRM` 훅 제거
- `PlanResolver` `getOneRM` 쿼리 제거
- 관련 테스트 제거
- `Volume` 모델의 `complete`, `oneRM` 속성 추가
- `VolumeFactory`, `VolumeInput`
- `Volume`모델의 `setOneRMWithTotal` 훅 추가
- `VolumeResolver` `getOneRM` 쿼리 추가
- 관련 테스트 추가
resolve #131
=> [feat] complete 속성 Volume 모델로 이동 및 getOneRM query 재디자인

src/resolvers/PlanResolver.ts, src/resolvers/TrainingResolver.ts
`Plan`, `Training`모델 삭제 리졸버에서 `Document` 삭제가 아닌 `Modal` 삭제로 변경
resolve #135
=> [fix] Document 삭제시 pre훅 동작하지 않음
